# Generated by Django 4.2.3 on 2023-07-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
