# Generated by Django 4.2.3 on 2023-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='prod_img/no_image.png', upload_to='prod_img'),
        ),
    ]
